FROM python:3.12-slim-bookworm
LABEL maintainer="sinfallas@gmail.com"

WORKDIR /app
RUN apt update && apt -y dist-upgrade && apt -y install --no-install-recommends --no-install-suggests nginx libnginx-mod-stream curl wget nano unzip zip freetds-dev freetds-bin unixodbc-dev tdsodbc && apt-get clean && rm -rf /var/lib/{apt,dpkg,cache,log} && apt -y autoremove
RUN pip install pyodbc sqlalchemy
EXPOSE 80
CMD /usr/sbin/nginx -g "daemon off;"
